language: python
sudo: false
python:
- 2.6
- 2.7
# pypy  # gipc doesn't support PyPy.
env:
  matrix:
  -
  - GEVENT_VERSION=1.1rc2 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1rc1 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1b6 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1b5 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1b4 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1b3 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1b2 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1b1 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1a2 GIPC_VERSION=0.5.0
  - GEVENT_VERSION=1.1a1 GIPC_VERSION=0.5.0
install:
- pip install coveralls
- |
  if [[ -z "$GEVENT_VERSION" ]]; then
    pip install gevent
  else
    pip install gevent==$GEVENT_VERSION
  fi
  if [[ -z "$GIPC_VERSION" ]]; then
    pip install gipc
  else
    pip install gipc==$GIPC_VERSION
  fi
  pip install -e .
script:
- coverage run --source=lets setup.py test
after_success:
- coveralls
