language: python
sudo: false
python:
- 2.7
- pypy
env:
  matrix:
  -
  - GEVENT_VERSION=1.1.2 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1.1 GIPC_VERSION=0.6.0
  - GEVENT_VERSION=1.1.0 GIPC_VERSION=0.6.0
install:
- pip install -U pytest
- pip install coveralls
- |
  if [[ -z "$GEVENT_VERSION" ]]; then
    pip install gevent
  else
    pip install gevent==$GEVENT_VERSION
  fi
  if [[ -z "$GIPC_VERSION" ]]; then
    pip install gipc
  else
    pip install gipc==$GIPC_VERSION
  fi
  pip install -e .
script:
- coverage run --source=lets setup.py test
after_success:
- coveralls
