language: python
sudo: false
python:
- 2.7
- pypy
env:
  matrix:
  -
  - GEVENT_VERSION=1.2a2
  - GEVENT_VERSION=1.2a1
  - GEVENT_VERSION=1.1.2
  - GEVENT_VERSION=1.1.1
  - GEVENT_VERSION=1.1.0
install:
- pip install -U pytest
- pip install coveralls
- |
  if [[ -z "$GEVENT_VERSION" ]]; then
    pip install gevent
  else
    pip install gevent==$GEVENT_VERSION
  fi
  pip install -e .
script:
- coverage run --source=lets setup.py test
after_success:
- coveralls
